# ─────────────────────────────────────────────────────────────────────────────
# Launch & Startup
# ─────────────────────────────────────────────────────────────────────────────

start-at-login = true

# Run these commands after Aerospace starts
after-startup-command = [
  'workspace 1', # Automatically switch to workspace 1
]

# ─────────────────────────────────────────────────────────────────────────────
# Layout Defaults
# ─────────────────────────────────────────────────────────────────────────────

enable-normalization-flatten-containers = false                         # Don't auto-flatten nested containers
enable-normalization-opposite-orientation-for-nested-containers = false # Preserve nested layout orientation
default-root-container-layout = 'tiles'                                 # Default layout mode is tiling
default-root-container-orientation = 'auto'                             # Auto-orient layout based on screen dimensions

# ─────────────────────────────────────────────────────────────────────────────
# MAIN MODE: Used to switch between functional modes
# ─────────────────────────────────────────────────────────────────────────────

[mode.main.binding]
cmd-ctrl-w = [
  "exec-and-forget open 'kmtrigger://macro=Mode%20HUD%20%E2%80%94%20Start&value=WINDOW%20MODE'",
  "mode window",
] # Enter window management mode

cmd-ctrl-r = [
  "exec-and-forget open 'kmtrigger://macro=Mode%20HUD%20%E2%80%94%20Start&value=RESIZE%20MODE'",
  "mode resize",
] # Enter resizing/layout mode

cmd-ctrl-v = [
  "exec-and-forget open 'kmtrigger://macro=Mode%20HUD%20%E2%80%94%20Start&value=VSERVICE%20MODE'",
  "mode vservice",
] # Enter config and utility mode

cmd-ctrl-f = 'fullscreen'            # Toggle fullscreen
alt-tab = 'workspace-back-and-forth' # Toggle between last two workspaces (Option+Tab)

# ─────────────────────────────────────────────────────────────────────────────
# WINDOW MODE: Move focus, rearrange windows, change workspaces
# ─────────────────────────────────────────────────────────────────────────────

[mode.window.binding]
h = 'focus left'       # Move focus left
j = 'focus down'       # Move focus down
k = 'focus up'         # Move focus up
l = 'focus right'      # Move focus right
shift-h = 'move left'  # Move window left
shift-j = 'move down'  # Move window down
shift-k = 'move up'    # Move window up
shift-l = 'move right' # Move window right


# Switch to specific workspaces
1 = 'workspace 1'
2 = 'workspace 2'
3 = 'workspace 3'
4 = 'workspace 4'
5 = 'workspace 5'
6 = 'workspace 6'
7 = 'workspace 7'
8 = 'workspace 8'
9 = 'workspace 9'
0 = 'workspace 10'
tab = 'workspace-back-and-forth' # Toggle between last two workspaces

# Move windows to specific workspaces
shift-1 = 'move-node-to-workspace 1'
shift-2 = 'move-node-to-workspace 2'
shift-3 = 'move-node-to-workspace 3'
shift-4 = 'move-node-to-workspace 4'
shift-5 = 'move-node-to-workspace 5'
shift-6 = 'move-node-to-workspace 6'
shift-7 = 'move-node-to-workspace 7'
shift-8 = 'move-node-to-workspace 8'
shift-9 = 'move-node-to-workspace 9'
shift-0 = 'move-node-to-workspace 10'

cmd-ctrl-w = 'mode window' # Re-enter window mode
cmd-ctrl-f = 'fullscreen' # Toggle fullscreen
esc = [
  "exec-and-forget open 'kmtrigger://macro=Mode%20HUD%20%E2%80%94%20Stop'",
  "mode main",
] # Exit to main mode
enter = [
  "exec-and-forget open 'kmtrigger://macro=Mode%20HUD%20%E2%80%94%20Stop'",
  "mode main",
] # Exit to main mode

# ─────────────────────────────────────────────────────────────────────────────
# RESIZE MODE: Resize windows and change layout
# ─────────────────────────────────────────────────────────────────────────────

[mode.resize.binding]
h = 'resize width -50'                 # Shrink window width
j = 'resize height +50'                # Grow window height
k = 'resize height -50'                # Shrink window height
l = 'resize width +50'                 # Grow window width
f = 'fullscreen'                       # Toggle fullscreen mode
d = 'layout tiles horizontal vertical' # Set layout to standard tiling
s = 'layout v_accordion'               # Vertical stacking layout
w = 'layout h_accordion'               # Horizontal stacking layout
e = 'layout tiles horizontal vertical' # Redundant tiling toggle (alias)
space = 'layout floating tiling'       # Toggle floating/tiling layout

esc = [
  "exec-and-forget open 'kmtrigger://macro=Mode%20HUD%20%E2%80%94%20Stop'",
  "mode main",
] # Return to main mode
enter = [
  "exec-and-forget open 'kmtrigger://macro=Mode%20HUD%20%E2%80%94%20Stop'",
  "mode main",
] # Return to main mode

# ─────────────────────────────────────────────────────────────────────────────
# VSERVICE MODE: Config actions and workspace reset
# ─────────────────────────────────────────────────────────────────────────────

[mode.vservice.binding]
c = 'flatten-workspace-tree' # Flatten current workspace layout
r = 'reload-config'          # Reload this config file

esc = [
  "exec-and-forget open 'kmtrigger://macro=Mode%20HUD%20%E2%80%94%20Stop'",
  "mode main",
] # Exit to main mode
enter = [
  "exec-and-forget open 'kmtrigger://macro=Mode%20HUD%20%E2%80%94%20Stop'",
  "mode main",
] # Exit to main mode


# ─────────────────────────────────────────────────────────────────────────────
# WINDOW FLOATING RULES: Set specific apps to float by default
# ─────────────────────────────────────────────────────────────────────────────

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']      # Float Finder

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = ['layout floating']   # Float Alacritty

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ['layout floating']           # Float Ghostty

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['layout floating'] # Float Obsidian

[[on-window-detected]]
if.app-id = 'cc.ffitch.shottr'
run = ['layout floating']      # Float Shottr

# ─────────────────────────────────────────────────────────────────────────────
# APP WORKSPACE ASSIGNMENT: Route specific apps to dedicated workspaces
# ─────────────────────────────────────────────────────────────────────────────

[[on-window-detected]]
if.app-id = 'com.jetbrains.pycharm'
run = ['move-node-to-workspace 3']  # Send PyCharm to workspace 3

[[on-window-detected]]
if.app-id = 'com.postmanlabs.mac'
run = ['move-node-to-workspace 4'] # Send Postman to workspace 4

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['move-node-to-workspace 10']     # Send Slack to workspace 10

# ─────────────────────────────────────────────────────────────────────────────
# FORCE WORKSPACES TO SPECIFIC MONITORS
# ─────────────────────────────────────────────────────────────────────────────

[workspace-to-monitor-force-assignment]
6 = '^built-in retina display$'  # Assign workspace 6 to internal display
7 = '^built-in retina display$'
8 = '^built-in retina display$'
9 = '^built-in retina display$'
10 = '^built-in retina display$'
